---
version: "2"
services:
  googlechrome:
    image: "olivercullimore/docker-chrome:latest"
    ports:
      - "${WEB_PORT}:5800"
      - "${VNC_PORT}:5900"
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      TZ: ${TZ}
      KEEP_APP_RUNNING: ${KEEP_APP_RUNNING}
      DISPLAY_WIDTH: ${DISPLAY_WIDTH}
      DISPLAY_HEIGHT: ${DISPLAY_HEIGHT}
      SECURE_CONNECTION: ${SECURE_CONNECTION}
      VNC_PASSWORD: ${VNC_PASSWORD}
      X11VNC_EXTRA_OPTS: ${X11VNC_EXTRA_OPTS}
    shm_size: ${SMH_SIZE}
    security_opt:
      - seccomp:unconfined
    volumes:
      - /portainer/Files/AppData/Config/GoogleChrome:/config
    restart: unless-stopped