---
version: "2"
services:
  worker:
    image: olivercullimore/media-grabber-worker
    links:
      - redis
    volumes:
      - /portainer/Files/AppData/media-grabber-worker:/data
    environment:
      - DATABASE=1
      - PASSWORD=${REDIS_PASSWORD}
      - FORMAT=best
      - OUTTMPL=${OUTPUT_TEMPLATE}
    restart: unless-stopped
    depends_on:
      - redis
  
  redis:
    image: redis
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    restart: unless-stopped