---
version: "2"
services:
  worker:
    image: olivercullimore/media-grabber-worker
    links:
      - redis
    volumes:
      - /portainer/Files/AppData/media-grabber-worker:/root/content
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - YTDL_FORMAT=${YTDL_FORMAT}
      - YTDL_OUTPUT_TEMPLATE=${YTDL_OUTPUT_TEMPLATE}
      - YTDL_PROXY=${YTDL_PROXY}
      - YTDL_WRITEINFOJSON=${YTDL_WRITEINFOJSON}
      - YTDL_VERBOSE=${YTDL_VERBOSE}
    restart: unless-stopped
    depends_on:
      - redis
  
  redis:
    image: redis
    command: redis-server --requirepass '${REDIS_PASSWORD}'
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped