---
version: "2"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "${NPM_HTTP_PORT}:80"
      - "${NPM_WEBUI_PORT}:81"
      - "${NPM_HTTPS_PORT}:443"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
    volumes:
      - /portainer/Files/AppData/Config/Nginx-Proxy/data:/data
      - /portainer/Files/AppData/Config/Nginx-Proxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: "jc21/mariadb-aria:latest"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped