---
version: "2"
services:
  wireguard:
    image: "ghcr.io/linuxserver/wireguard:latest"
    ports:
      - "${SERVERPORT}:51820"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SERVERURL: ${SERVERURL}
      SERVERPORT: ${SERVERPORT}
      PEERS: ${PEERS}
      PEERDNS: ${PEERDNS}
      INTERNAL_SUBNET: ${INTERNAL_SUBNET}
      ALLOWEDIPS: ${ALLOWEDIPS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /portainer/Files/AppData/Config/WireGuard/config:/config
      - /portainer/Files/AppData/Config/WireGuard/lib_modules:/lib/modules
    restart: unless-stopped